### PR TITLE
Do no specify slurm account in config (default to the one that the user belongs to)

### PR DESCRIPTION
**Pull request by garciagenrique**

### CODE REVIEW

**Review by vuillaut — CHANGES_REQUESTED** [review]
change in template as well ?

**Comment by garciagenrique** [comment]
> change in template as well ?

Yes, this way we don't need to change it us later (user MC prods are gonna be launched from this user so that they will be centralised).

**Comment by morcuended** [comment]
Why not leave it by default to whichever account the user belongs to?

**Comment by garciagenrique** [comment]
> Why not leave it by default to whichever account the user belongs to? (without the need of explicitly specifying it)

You are right. Even more that this arg is optional

**Pull request merged**
