### PR TITLE
Update lstchain config and version to v0.9.7

### PR DESCRIPTION
**Pull request by vuillaut**

### CODE REVIEW

**Comment by rlopezcoto** [comment]
Being discussed on slack now, https://github.com/cta-observatory/cta-lstchain/pull/1028 proposed a solution and we will release v0.9.7.post1 if there are no other problems or v0.9.8 if there are additional changes

**Review by vuillaut — COMMENTED** [review]
lstchain v0.9.9 in cond_env base config

**Review by vuillaut — COMMENTED** [review]
lstchain v0.9.9 in conda_env base config

**Review by vuillaut — COMMENTED** [review]
remove requirements on ctaplot and ctapipe_io_lst versions

**Pull request merged**
