### PR TITLE
20221006 src3 test nodes

### PR DESCRIPTION
**Pull request by SeiyaNozaki**
# New Prod config

## Prod_ID
20221006_src3_test_nodes

## Short description of the config
produce Test DL1 datasets including newly produced test MCs (`theta_23.630_az_100.758` and `theta_23.630_az_259.265`)
This production config includes only DL1ab and DL1 merge process

### CODE REVIEW

**Review by vuillaut — APPROVED** [review]
Hi @SeiyaNozaki 
Looks good to me.
Note that you used a version of lstmcpipe that is not a release (master ?). It's fine, this will work and I can retrieve the exact commit you used but in general, you are encouraged to use tagged versions, it will be much easier to re-run the prod if needed in the future.

**Comment by SeiyaNozaki** [comment]
Hi @vuillaut 
> you are encouraged to use tagged versions,

ah ok, thanks... I will do so next time.
I was not sure how to deactivate `run_checker` flag which raised an error (because there are more simtel files now than before), so I just modified the code directly just to create the production config without this flag in the end...

**Comment by vuillaut** [comment]
> Hi @vuillaut
> 
> > you are encouraged to use tagged versions,
> 
> ah ok, thanks... I will do so next time. I was not sure how to deactivate `run_checker` flag which raised an error (because there are more simtel files now than before), so I just modified the code directly just to create the production config without this flag in the end...

Thank for reporting the issue!
I have prepared #347 to fix this.
I will take care of this prod now.

**Comment by vuillaut** [comment]
Ha but you left out these new nodes in the lstmcpipe config file, so it (rightfully) complains that it can't find the corresponding DL1 files.
Fix #347 seems to work find, I have regenerated the config using the command line you provided in the README (thanks for including it) and launched the production. I will let you know how it goes 🚀

**Comment by SeiyaNozaki** [comment]
ah you're right... Thank you @vuillaut !

**Pull request merged**
