### PR TITLE
Fix 20221025 src4 high nsb lza

### LINKED ISSUE #358: `20221025_src4_high_NSB_LZA` wrong lstchain config
Two issues in that prod:
- the lstchain config is wrong (can't be read) - this should have not pass the unit tests --> to check
- the NSB tuning is applied only in the DL1ab stage, so I must produce base DL1 first  and then start from new prod

@FrancaCassol

### PR DESCRIPTION
**Pull request by vuillaut**
Hi @FrancaCassol 

I fixed the lstchain config and reproduced the lstmcpipe config applying the DL1ab process to the DL1 produced without tuning.

Fixes #358

### CODE REVIEW

**Review by FrancaCassol — APPROVED** [review]

**Comment by vuillaut** [comment]
🚀

**Comment by vuillaut** [comment]
@FrancaCassol We have another error in DL1ab stage on this prod:
``` 
Traceback (most recent call last):
  File "/fefs/aswg/software/conda/envs/lstchain-v0.9.9/bin/lstchain_dl1ab", line 8, in <module>
    sys.exit(main())
  File "/fefs/aswg/software/conda/envs/lstchain-v0.9.9/lib/python3.8/site-packages/lstchain/scripts/lstchain_dl1ab.py", line 113, in main
    increase_psf = imconfig["increase_psf"]
KeyError: 'increase_psf'
```

**Comment by FrancaCassol** [comment]
Hi @vuillaut , 
I have not idea concerning this error, I just added the NSB tuning to the standard lstchain config file (as I did for my previous production, which worked), I did not touch the psf cards and  I even do not see it in the config. @moralejo can you perhaps help ?

**Comment by vuillaut** [comment]
Fixed in #368 and relaunched

**Pull request merged**
