### PR TITLE
20230124 src6 dec2276 tuned

### PR DESCRIPTION
**Pull request by alvmas**
# New Prod config

Self check-list:

- [x] I have checked the lstchain config, in particular for:
  - [x] `az_tel` instead of `sin_az_tel` if data to be analyzed have been produced with lstchain <= v0.9.7
  - [x] "increase_nsb" and "increase_psf" are provided in "image_modifier" (if used)
- [x] I have checked the environment in the lstmcpipe config and it is the one used to analyse DL>1 data
- [x] I have provided the command (in README), or script (in additionnal .py file) used to produce the lstmcpipe config

## Prod_ID
20230124 src6 dec2276 tuned

## Short description of the config
Configuration file with src-dependent analysis and tunning for src6 at dec=22.76.

## Why this config is needed 
New MC with specific tunning for a new source (src6)

### CODE REVIEW

**Comment by vuillaut** [comment]
The tests are failing because
``` 
ValueError: Integration correction must be applied to MC for the image extractor:
config['LocalPeakWindowSum']['apply_integration_correction'] = True
```

**Review by vuillaut — APPROVED** [review]
LGTM

**Comment by vuillaut** [comment]
🚀

**Comment by vuillaut** [comment]
Hi @alvmas,

I noticed that there are new test nodes that have not been processed in the base production, and therefore are not included here either:
```
/fefs/aswg/software/conda/envs/lstchain-v0.9.12/lib/python3.8/site-packages/lstmcpipe/config/paths_config.py:995: UserWarning: /fefs/aswg/data/mc/DL1/AllSky/20221215_v0.9.12_base_prod/TestingDataset/node_theta_43.113_az_28.023_ does not exist but MC file for node_theta_43.113_az_28.023_ does. This node will be removed from production.
  warnings.warn(
/fefs/aswg/software/conda/envs/lstchain-v0.9.12/lib/python3.8/site-packages/lstmcpipe/config/paths_config.py:995: UserWarning: /fefs/aswg/data/mc/DL1/AllSky/20221215_v0.9.12_base_prod/TestingDataset/node_theta_43.113_az_331.997_ does not exist but MC file for node_theta_43.113_az_331.997_ does. This node will be removed from production.
  warnings.warn(
/fefs/aswg/software/conda/envs/lstchain-v0.9.12/lib/python3.8/site-packages/lstmcpipe/config/paths_config.py:995: UserWarning: /fefs/aswg/data/mc/DL1/AllSky/20221215_v0.9.12_base_prod/TestingDataset/node_theta_75.226_az_136.586_ does not exist but MC file for node_theta_75.226_az_136.586_ does. This node will be removed from production.
  warnings.warn(
/fefs/aswg/software/conda/envs/lstchain-v0.9.12/lib/python3.8/site-packages/lstmcpipe/config/paths_config.py:995: UserWarning: /fefs/aswg/data/mc/DL1/AllSky/20221215_v0.9.12_base_prod/TestingDat
aset/node_theta_75.226_az_109.015_ does not exist but MC file for node_theta_75.226_az_109.015_ does. This node will be removed from production.
  warnings.warn(
/fefs/aswg/software/conda/envs/lstchain-v0.9.12/lib/python3.8/site-packages/lstmcpipe/config/paths_config.py:995: UserWarning: /fefs/aswg/data/mc/DL1/AllSky/20221215_v0.9.12_base_prod/TestingDataset/node_theta_75.226_az_175.158_ does not exist but MC file for node_theta_75.226_az_175.158_ does. This node will be removed from production.
  warnings.warn(
/fefs/aswg/software/conda/envs/lstchain-v0.9.12/lib/python3.8/site-packages/lstmcpipe/config/paths_config.py:995: UserWarning: /fefs/aswg/data/mc/DL1/AllSky/20221215_v0.9.12_base_prod/TestingDataset/node_theta_82.155_az_79.122_ does not exist but MC file for node_theta_82.155_az_79.122_ does. This node will be removed from production.
  warnings.warn(
/fefs/aswg/software/conda/envs/lstchain-v0.9.12/lib/python3.8/site-packages/lstmcpipe/config/paths_config.py:995: UserWarning: /fefs/aswg/data/mc/DL1/AllSky/20221215_v0.9.12_base_prod/TestingDataset/node_theta_46.37_az_30.246_ does not exist but MC file for node_theta_46.37_az_30.246_ does. This node will be removed from production.
  warnings.warn(
/fefs/aswg/software/conda/envs/lstchain-v0.9.12/lib/python3.8/site-packages/lstmcpipe/config/paths_config.py:995: UserWarning: /fefs/aswg/data/mc/DL1/AllSky/20221215_v0.9.12_base_prod/TestingDataset/node_theta_49.458_az_31.603_ does not exist but MC file for node_theta_49.458_az_31.603_ does. This node will be removed from production.
  warnings.warn(
/fefs/aswg/software/conda/envs/lstchain-v0.9.12/lib/python3.8/site-packages/lstmcpipe/config/paths_config.py:995: UserWarning: /fefs/aswg/data/mc/DL1/AllSky/20221215_v0.9.12_base_prod/TestingDataset/node_theta_49.458_az_328.397_ does not exist but MC file for node_theta_49.458_az_328.397_ does. This node will be removed from production.
  warnings.warn(
/fefs/aswg/software/conda/envs/lstchain-v0.9.12/lib/python3.8/site-packages/lstmcpipe/config/paths_config.py:995: UserWarning: /fefs/aswg/data/mc/DL1/AllSky/20221215_v0.9.12_base_prod/TestingDataset/node_theta_75.226_az_213.73_ does not exist but MC file for node_theta_75.226_az_213.73_ does. This node will be removed from production.
  warnings.warn(
/fefs/aswg/software/conda/envs/lstchain-v0.9.12/lib/python3.8/site-packages/lstmcpipe/config/paths_config.py:995: UserWarning: /fefs/aswg/data/mc/DL1/AllSky/20221215_v0.9.12_base_prod/TestingDataset/node_theta_82.155_az_271.199_ does not exist but MC file for node_theta_82.155_az_271.199_ does. This node will be removed from production.
  warnings.warn(
/fefs/aswg/software/conda/envs/lstchain-v0.9.12/lib/python3.8/site-packages/lstmcpipe/config/paths_config.py:995: UserWarning: /fefs/aswg/data/mc/DL1/AllSky/20221215_v0.9.12_base_prod/TestingDataset/node_theta_46.37_az_329.754_ does not exist but MC file for node_theta_46.37_az_329.754_ does. This node will be removed from production.
  warnings.warn(
/fefs/aswg/software/conda/envs/lstchain-v0.9.12/lib/python3.8/site-packages/lstmcpipe/config/paths_config.py:995: UserWarning: /fefs/aswg/data/mc/DL1/AllSky/20221215_v0.9.12_base_prod/TestingDataset/node_theta_75.226_az_31.342_ does not exist but MC file for node_theta_75.226_az_31.342_ does. This node will be removed from production.
```

**Comment by alvmas** [comment]
Hi @vuillaut,
Should I run again the script to generate the config file? Why is this happening? I can see that all test nodes are above 40 so this should not be too problematic but I would like to have those nodes as well for the future.

**Comment by vuillaut** [comment]
This is likely happening because these nodes have been produced after `20221215_v0.9.12_base_prod` - there is nothing you can do about it right now.
We shall make a new base production for everyone to have them in their analysis, I just wanted to let you know and make sure they were not critical to you current analysis.

Your current analysis is already running 🚂

**Pull request merged**
