### PR TITLE
Create lstchain_mc_dl2_to_irfs.py

### PR DESCRIPTION
**Pull request by vuillaut**

### CODE REVIEW

**Comment by garciagenrique** [comment]
🥳 🥳 🥳 🥳 
Speaking about the tree path, a do you think that saving the irfs into a `IRFs` directory (at the same level that `running_analysis`, `dl1` etc...) will be ok ? inside `analysis_logs` maybe ? Or would you prefer to keep them "home made" for the moment and save them elsewhere ?

**Comment by garciagenrique** [comment]
Will 🧐🧐🧐  the code now carefully 😛

**Comment by garciagenrique** [comment]
@vuillaut can we then close this PR  ?

**Comment by vuillaut** [comment]
Replaced by PR #89

**Pull request closed without merging**
