### PR TITLE
Voutsi seasonal atmosphere

### PR DESCRIPTION
**Pull request by vuillaut**
Duplicate of #432 for tests

### CODE REVIEW

**Comment by vuillaut** [comment]
@Voutsi Sorry I had to duplicate your PR for tests requiring internal data

Could you have a look at the config please? It seems not to be valid
https://github.com/cta-observatory/lstmcpipe/actions/runs/6630900759/job/18013284433?pr=435

**Comment by Voutsi** [comment]
Hi @vuillaut 

you are right, thanks, there was an indentation error. I fixed it in the original PR, it seems that I don't have permissions to push something here.

**Comment by vuillaut** [comment]
> Hi @vuillaut
> 
> you are right, thanks, there was an indentation error. I fixed it in the original PR, it seems that I don't have permissions to push something here.

You should request Max or Karl to be added to cta-observatory github organisation so I can add you to lst-dev and then you will be able to create branches directly in this repo to allow unit tests to run for your PRs.
In the  meantime I will synch with you branch.

**Comment by Voutsi** [comment]
I see, it detects some tab characters that it doesn't accept. I will fix it.

**Comment by Voutsi** [comment]
So it seems the problem is fixed. I launched the command 
```lstmcpipe -c config_MC_prod.yml -conf_lst lstchain_*.json```
and it reached the stage
```Are you sure ? [y/N]```
If I understood well, that should mean the the configuration is valid

**Comment by vuillaut** [comment]
> So it seems the problem is fixed. I launched the command `lstmcpipe -c config_MC_prod.yml -conf_lst lstchain_*.json` and it reached the stage `Are you sure ? [y/N]` If I understood well, that should mean the the configuration is valid

Hi
You can validate the config using `lstmcpipe_validate_config` command

**Comment by vuillaut** [comment]
seems good now

**Comment by vuillaut** [comment]
Prod is done @Voutsi

**Pull request merged**
