### PR TITLE
Update CI.yml

### PR DESCRIPTION
**Pull request by garciagenrique**
CI syntax was not correct: https://github.com/cta-observatory/lstmcpipe/actions/runs/3002594699

### CODE REVIEW

**Review by vuillaut — CHANGES_REQUESTED** [review]
why moving this line here?
I'd prefer it to stay where it was, or in  the future this comment won't make sens.
I think the problem was the indent?

**Comment by garciagenrique** [comment]
> why moving this line here? I'd prefer it to stay where it was, or in the future this comment won't make sens. I think the problem was the indent?

Exactly, the indent. Now, GitHub does not have CI validator, the only way I found to check that the CI file is valid was by editing it using GitHub (not the github.dev !), that underlines in red the lines that are not correct.  

Feel free to push to this PR in the moment you find a valid syntax.

**Review by vuillaut — APPROVED** [review]

**Comment by vuillaut** [comment]
Here is what I meant.
If ok with you, you can merge.

**Comment by garciagenrique** [comment]
> Here is what I meant. If ok with you, you can merge.

The editor did not like this option either, but if it works, of course I'm ok

**Comment by garciagenrique** [comment]
FYI, testing it on #336

**Pull request merged**
