### PR TITLE
Add full production with standard NSB/PSF for AGN analysis

### PR DESCRIPTION
**Pull request by mireianievas**
# New Prod config

Self check-list:

- [ x] I have checked the lstchain config, in particular for:
  - [ x] `az_tel` instead of `sin_az_tel` if data to be analyzed have been produced with lstchain <= v0.9.7
  - [ x] "increase_nsb" and "increase_psf" are provided in "image_modifier" (if used)
- [ x] I have checked the environment in the lstmcpipe config and it is the one used to analyse DL>1 data
- [ x] I have provided the command (in README), or script (in additionnal .py file) used to produce the lstmcpipe config

## Prod_ID

20221215_v0.9.12_base_prod

## Short description of the config

Standard NSB standard PSF for processing standard AGN dark data. 

Declination tracks needed:

- dec_2276 
- dec_3476 
- dec_4822 
- dec_6676 
- dec_931
- dec_min_413 

While some sources may require tuned NSB, I want to check myself how an incorrect NSB spoils the reconstruction 

## Why this config is needed 

The last full production (DL1 + models) that is available is from ~ May. Since then, mostly incomplete productions and tuned ones for specific sources.

### CODE REVIEW

**Comment by vuillaut** [comment]
What version (or how did you install it) of lstmcpipe did you use to generate the config?
The config shows a dev v0.1+ version.
Did you need to modify lstmcpipe? If not please use a tagged version (0.10 is the last one) so we can reproduce these results.

**Comment by mireianievas** [comment]
Ok, I used the main repository, synced today. Let me update the pull request config file using a tagged version.

**Comment by mireianievas** [comment]
Done.

**Comment by vuillaut** [comment]
Another thing.
I notice you left `sin_az_tel` in the config. Be aware that all real data produced with lstchain <= v0.9.7 can't be analyzed that way. Is that ok ?

**Comment by mireianievas** [comment]
But I can reprocess those old data, right? My idea is to have an homogeneous processing of the entire datasets with a new lstchain.

**Comment by vuillaut** [comment]
> But I can reprocess those old data, right? My idea is to have an homogeneous processing of the entire datasets with a new lstchain.

You can, it's usually done by lstosa though.

**Comment by vuillaut** [comment]
Merging and launching prod

**Comment by vuillaut** [comment]
🚀

**Comment by mireianievas** [comment]
@vuillaut I just learnt that the azimuth -> sin(az) change was recently reversed, so now it is decided we will use azimuth again. Shall I make, for the sake of consistency, a new pull request with that parameter in the model generation?

**Pull request merged**
