### PR TITLE
20230921 v0.10.4 src3 dec3476 4822 tuned from Seiya

### PR DESCRIPTION
**Pull request by vuillaut**
Duplicate of #422 to allow download data to pass (it needs the secret which is in this repo).
Closes #422

### CODE REVIEW

**Comment by vuillaut** [comment]
@SeiyaNozaki prod launched 🚀 
should be ready tonight

**Comment by SeiyaNozaki** [comment]
@vuillaut I realized dl1 to dl2, dl2 to irf step were not described in the config file even though I used `PathConfigAllSkyFullDL1ab` as input arguments.  Did I do something wrong...?

**Comment by vuillaut** [comment]
Hi @SeiyaNozaki 
There was an error in the config, a typo in the original prod id : `20230901_v0.10.4_allysky_base_prod` instead of `20230901_v0.10.4_allsky_base_prod` (subtle diff).
I manually corrected it here (should not have) but the harm was done, files had been removed when you generated the config. You probably saw many warnings of the type:
```
UserWarning: /fefs/aswg/data/mc/DL1/AllSky/20230901_v0.10.4_allysky_base_prod/TestingDataset/node_theta_32.059_az_175.158_ does not exist but MC file for node_theta_32.059_az_175.158_ does. This node will be removed from production.
```

Could you review #425 please?

**Comment by SeiyaNozaki** [comment]
ahhh right... I didn't care about the warning messages too much since a config file was generated... Thank you for spotting my mistake... I already approved #425

**Pull request merged**
