### PR TITLE
Running from dl0 to IRFs for dec_4822

### PR DESCRIPTION
**Pull request by giorgio-pirola**
# New Prod config

### CODE REVIEW

**Comment by vuillaut** [comment]
hi.
Thank you for the PR.
Could you add to the README the command you used to generate the config please?

**Comment by vuillaut** [comment]
Thank you.
Could you as well refer to the source you are requesting this prod for from https://www.lst1.iac.es/wiki/index.php/MC_analysis_and_IRF_production#lstmcpipe_productions (or add it in the table if it's not there) in the readme please?

+ pull and merge master in your branch, it will trigger the CI with the config validation.

**Comment by vuillaut** [comment]
Also, these files should be added in a subdirectory of `production_configs`

**Comment by vuillaut** [comment]
The configs are valid.

**Comment by giorgio-pirola** [comment]
> Also, these files should be added in a subdirectory of `production_configs`



> Thank you. Could you as well refer to the source you are requesting this prod for from https://www.lst1.iac.es/wiki/index.php/MC_analysis_and_IRF_production#lstmcpipe_productions (or add it in the table if it's not there) in the readme please?
> 
> also, pull and merge master in your branch, it will trigger the CI with the config validation.

So I added the pull request in the table on the wiki page. I didn't quite get if should I also mention the source in the README file.
And secondly, I saw your last message saying the config are valid. NDo I still need to pull and and merge the master to my branch?

**Comment by vuillaut** [comment]
Yes you will have to merge the master branch please, there was an issue with protobuf messing with the install and unit tests

**Comment by vuillaut** [comment]
@giorgio-pirola 
Can I also ask you to add the following to each IRF production stage please?
`slurm_options: --mem=6GB`

We noticed some memory requirement issues for some nodes (see issue #309) and this would prevent issues for this prod as well.

**Comment by vuillaut** [comment]
I have modified the prod ID to `20220524_dec_4822_tuned` to be consistent with others and started the prod 🚀

**Pull request merged**
