### PR TITLE
add new production for src3 with tuned NSB for moon data analysis

### PR DESCRIPTION
**Pull request by joteros**
# New Prod config

Self check-list:

- [X] I have checked the lstchain config, in particular for:
  - [X] `az_tel` instead of `sin_az_tel` if data to be analyzed have been produced with lstchain <= v0.9.7
  - [X] "increase_nsb" and "increase_psf" are provided in "image_modifier" (if used)
- [X] I have checked the environment in the lstmcpipe config and it is the one used to analyse DL>1 data
- [X] I have provided the command (in README), or script (in additionnal .py file) used to produce the lstmcpipe config

## Prod_ID
20240426_v0.10.9_src3_dec3476_4822_tunedNSB

## Short description of the config
Config for a source with dec within 3476/4822 and NSB tuning:

    "image_modifier": {
       "increase_nsb": true,
       "extra_noise_in_dim_pixels": 6.974,
       "extra_bias_in_dim_pixels": 1.825,
       "transition_charge": 8,
       "extra_noise_in_bright_pixels": 4.195
    }

lstmcpipe_generate_config PathConfigAllSkyFull --prod_id 20240426_v0.10.9_src3_dec3476_4822_tunedNSB --dec_list dec_3476 dec_4822

## Why this config is needed 
See wiki page (src 3)
https://www.lst1.iac.es/wiki/index.php/MC_analysis_and_IRF_production#lstmcpipe_productions

### CODE REVIEW

**Review by vuillaut — APPROVED** [review]

**Comment by vuillaut** [comment]
Prod started 🚀

**Comment by morcuended** [comment]
@vuillaut, it seems that some jobs from this prod did not finish correctly, can you please check?

**Comment by vuillaut** [comment]
hi @morcuended , could you be more specific please? I don't see any job from this prod pending or in fail and I can see the DL2 have been produced

**Comment by morcuended** [comment]
Indeed, my bad, those other pending jobs were from another prod. Files from this one look good. Thanks!

**Pull request merged**
