### PR TITLE
Test prod script

### PR DESCRIPTION
**Pull request by vuillaut**
Small script to generate a mini prod tree on the cluster with its paths config

### CODE REVIEW

**Comment by garciagenrique** [comment]
Imo, I don't think this script is needed in the lib.

**Comment by vuillaut** [comment]
We'll need this script in the future, I'd like to save it somewhere. Where should I put it ?

**Review by garciagenrique — CHANGES_REQUESTED** [review]
data_test directory at LP doesn't contain off0.4deg gammas (I added by hand). If we create a test_subsample, please include all particles to check a real (although small) workflow.

**Comment by vuillaut** [comment]
> data_test directory at LP doesn't contain off0.4deg gammas (I added by hand). If we create a test_subsample, please include all particles to check a real (although small) workflow.

Regenerate using the up-to-date script please.

**Review by garciagenrique — APPROVED** [review]
Thanks @vuillaut !

**Pull request merged**
