### PR TITLE
Run prod. 20221108_galsource_min_413_tuned_nsb

### PR DESCRIPTION
**Pull request by aaguasca**
# New Prod Config

## Prod_ID

20221108_galsource_min_413_tuned_nsb

## Short description of the config

dec_min_413 with NSB tuning to galactic source.

## Why this config is needed

Reprocess with the latest version of lstchain v0.9.9. Previous prod_id is `galsource_min_413_tuned_nsb`.

## Other information

RF features following issue #369

### command-line:
```
lstmcpipe_generate_config PathConfigAllSkyFullDL1ab --prod_id 20221108_galsource_min_413_tuned_nsb --kwargs source_prod_id=20221027_v0.9.9_base_prod --dec_list dec_min_413
```

### CODE REVIEW

**Comment by vuillaut** [comment]
Hi @aaguasca 
Is that galactic source listed in [the wiki](https://www.lst1.iac.es/wiki/index.php/MC_analysis_and_IRF_production#lstmcpipe_productions)?
If not, could you add it, giving it a number please? It will help others analysers link it to that prod.
Thanks.

**Comment by aaguasca** [comment]
> Hi @aaguasca Is that galactic source listed in [the wiki](https://www.lst1.iac.es/wiki/index.php/MC_analysis_and_IRF_production#lstmcpipe_productions)? If not, could you add it, giving it a number please? It will help others analysers link it to that prod. Thanks.
Yes, it is src1. Thank you for the reminder.

**Comment by vuillaut** [comment]
> > Hi @aaguasca Is that galactic source listed in [the wiki](https://www.lst1.iac.es/wiki/index.php/MC_analysis_and_IRF_production#lstmcpipe_productions)? If not, could you add it, giving it a number please? It will help others analysers link it to that prod. Thanks.
> 
> Yes, it is src1. Thank you for the reminder.

Ok great.
Could you add that ID in the readme please? So it's findable when doing a search in the documentation.

**Review by vuillaut — APPROVED** [review]
LGTM

**Comment by vuillaut** [comment]
Running 🚀

**Pull request merged**
