### PR TITLE
create configuration for the chosen source

### PR DESCRIPTION
**Pull request by gabriele-panebianco-inaf**
# New Prod config

Self check-list:

- [x] I have checked the lstchain config, in particular for:
  - [x] `az_tel` instead of `sin_az_tel` if data to be analyzed have been produced with lstchain <= v0.9.7
  - [x] "increase_nsb" and "increase_psf" are provided in "image_modifier" (if used)
- [x] I have checked the environment in the lstmcpipe config and it is the one used to analyse DL>1 data
- [x] I have provided the command (in README), or script (in additionnal .py file) used to produce the lstmcpipe config

## Prod_ID
20230315_src_dec2276_tuned_nsb

## Short description of the config
Config for a galactic source with dec 22.47 and specific NSB tuning.

## Why this config is needed 
Processing of data taken from a galactic source which has a particular NSB level.

### CODE REVIEW

**Comment by vuillaut** [comment]
Hi
Thank you for the PR and for the detailed README!
Are you sure you want to process with `lstchain-v0.9.9`, which is not the latest env available? (see lstmcpipe config).

The cluster seems down at the moment, I will let you know when these can be processed.

**Comment by gabriele-panebianco-inaf** [comment]
Hi @vuillaut, sorry for the late reply.
Thank you, I updated the requested lstchain to v0.9.13. I don't know why there was v0.9.9, I run the script in the v0.9.13 environment.

I have some questions on the procedure to get the appropriate configuration files for the simulations. I got them by running
```
lstmcpipe_generate_config PathConfigAllSkyFullDL1ab --dec_list dec_2276 --prod_id 20230315_src_dec2276_tuned_nsb --kwargs source_prod_id=20230315_src_dec2276_tuned_nsb
```
is this the proper way to get them?
- I am not sure about the difference between `--prod_id` and `--kwargs source_prod_id`.
- I can see on the cluster real DL1 data are processed with a configuration file named `lstchain_config_v0.9.4_from2022onwards`, which is slightly different in some fields from the file produced by `lstmcpipe_generate_config`. Which one should we use for simulations?
- In `lstmcpipe_config.yml` I got the fields `dl1_to_dl2` and `dl2_to_irfs` are empty. Is this normal?

**Comment by vuillaut** [comment]
Hi,

> Hi @vuillaut, sorry for the late reply. Thank you, I updated the requested lstchain to v0.9.13. I don't know why there was v0.9.9, I run the script in the v0.9.13 environment.

This is independent, as you can choose to run the production in the environment you like.
Nevertheless, lstmcpipe config proposes one env (but was not up to date in this case).

> 
> I have some questions on the procedure to get the appropriate configuration files for the simulations. I got them by running
> 
> ```
> lstmcpipe_generate_config PathConfigAllSkyFullDL1ab --dec_list dec_2276 --prod_id 20230315_src_dec2276_tuned_nsb --kwargs source_prod_id=20230315_src_dec2276_tuned_nsb
> ```
> 
> is this the proper way to get them?

For the lstmcpipe config, yes.
Note that you are here following this workflow:
https://cta-observatory.github.io/lstmcpipe/pipeline.html#dl1ab

> 
> * I am not sure about the difference between `--prod_id` and `--kwargs source_prod_id`.

The prod_id is the one you want to produce.
The source_prod_id is the one you want to start from (the base one). See the doc and let me know if that is still not clear.

> * I can see on the cluster real DL1 data are processed with a configuration file named `lstchain_config_v0.9.4_from2022onwards`, which is slightly different in some fields from the file produced by `lstmcpipe_generate_config`. Which one should we use for simulations?

- What are the differences ?
- In `lstchain_config_v0.9.4_from2022onwards`, only the config for the R0 to DL1 processing is important and should be the same for the MC production. Other parameters (DL1-->DL2) are up to you, but the standard config from lstchain is a good start.

> * In `lstmcpipe_config.yml` I got the fields `dl1_to_dl2` and `dl2_to_irfs` are empty. Is this normal?

No.
But since you try to start from a non-existing source prod `20230315_src_dec2276_tuned_nsb`, you probably got an error when trying to generate the config?
You probably want to start from something like [20230127_v0.9.12_base_prod_az_tel](https://github.com/cta-observatory/lstmcpipe/tree/master/production_configs/20230127_v0.9.12_base_prod_az_tel)

**Comment by gabriele-panebianco-inaf** [comment]
> You probably want to start from something like [20230127_v0.9.12_base_prod_az_tel](https://github.com/cta-observatory/lstmcpipe/tree/master/production_configs/20230127_v0.9.12_base_prod_az_tel)

Thank you, now the `lstmcpipe_config.yml` makes sense.

------------------------------------------------
> What are the differences ?

Regarding the `lstchain_config.yml`and the differences with  `lstchain_config_v0.9.4_from2022onwards` there are differences such as:
- `lstchain_config_v0.9.4_from2022onwards` in the various `"random_forest_\*_\*_args"`  has "max_depth": 50 or 100, "min_samples_leaf": 2, "n_jobs": 4,"min_samples_split": 2. The lstmcpipe script produces (30,10,-1,10)
- `lstchain_config_v0.9.4_from2022onwards` lacks `"n_training_events"`, which is included by the lstmcpipe script
- `lstchain_config_v0.9.4_from2022onwards` in the various `"\*_regression_features"` lacks "sin_az_tel","alt_tel", which are included by the lstmcpipe script
- `lstchain_config_v0.9.4_from2022onwards` in `"LocalPeakWindowSum"` and `"GlobalPeakWindowSum"` uses "apply_integration_correction": false, the lstmcpipe script uses true.

As it is the first time I request models, I have no idea if they are important or not.

**Comment by vuillaut** [comment]
> > What are the differences ?
> 
> Regarding the `lstchain_config.yml`and the differences with `lstchain_config_v0.9.4_from2022onwards` there are differences such as:
> 
> * `lstchain_config_v0.9.4_from2022onwards` in the various `"random_forest_\*_\*_args"`  has "max_depth": 50 or 100, "min_samples_leaf": 2, "n_jobs": 4,"min_samples_split": 2. The lstmcpipe script produces (30,10,-1,10)
> * `lstchain_config_v0.9.4_from2022onwards` lacks `"n_training_events"`, which is included by the lstmcpipe script
> * `lstchain_config_v0.9.4_from2022onwards` in the various `"\*_regression_features"` lacks "sin_az_tel","alt_tel", which are included by the lstmcpipe script
> * `lstchain_config_v0.9.4_from2022onwards` in `"LocalPeakWindowSum"` and `"GlobalPeakWindowSum"` uses "apply_integration_correction": false, the lstmcpipe script uses true.
> 
> As it is the first time I request models, I have no idea if they are important or not.

For everything related to RF models, you should use the lstmcpipe config (which comes from the lstchain standard MC config).

The `apply_integration_correction` should indeed be set to True for MC analysis.

**Comment by gabriele-panebianco-inaf** [comment]
Perfect, thank you so much! Then the current commit and files seems to be okay and ready.

**Review by vuillaut — APPROVED** [review]

**Pull request merged**
